version: '2'
services:
    app:
        image: tf-od-api 
        #network_mode: host
        ports:
          - 80:5000
        volumes:
        - ./tensorflow/:/tensorflow
        environment:
          #PORT: 5000
          FLASK_DEBUG: 1

